### ISSUE TITLE
Group ansible does not exist

### ISSUE THREAD

**Issue by aguerrave** [LearnLinuxTV/personal_ansible_desktop_configs#2]
Hi,
I'm trying to use your skeleton to configure my personal ansible, but I can't figure out how to correct this error?
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Group ansible does not exist"}
Another question: the role for laptops vs workstation, What is the most different. Or you use the same.
Regards.

**Comment by borcean** [comment]
Please give more context to the error you are getting. At a minimum give the whole task that failed so we can see the name, like so:

```
TASK [base : ansible setup | ansible systemd timers] ****************************************************************************
ok: [neon.borcean.xyz] => (item={'key': 'refresh', 'value': {'timer_boot': '1m', 'timer_active': '1d'}})
ok: [neon.borcean.xyz] => (item={'key': 'pull', 'value': {'timer_boot': '10m', 'timer_active': '1h'}})

```

Based on what you have posted I am assuming its [`base: ansible setup | create ansible log file`.](https://github.com/LearnLinuxTV/personal_ansible_desktop_configs/blob/9f7b093a396ec8fd1aaeabdb17601c5da241c3fb/roles/base/tasks/ansible_setup.yml#L21) If so the ansible group simply does not exist on your system. Jay likely creates that group *before* ansible is run for the first time using some script that seeds his setup.


I have [forked and adapted Jay's repo to fit my own needs,]( https://github.com/borcean/ansible-configs) you may want to take a look and see if it gives you some ideas 🙂 

With respect to "laptops vs workstation" I think of every PC, be it a laptop or desktop, as a workstation. For all PCs I want the workstation role run, but on my laptop I *also* run a second role called thinkpad that configures power settings, etc. See the [hosts](https://github.com/borcean/ansible-configs/blob/main/hosts) file.

**Comment by aguerrave** [comment]
Hi, thank for response. 
In the roles->task->users->jay.yml
```
- name: users | jay | create user
  tags: jay,sudo,users
  user:
    name: jay
    group: jay
    **groups: adm,ansible,{{ sudo_group }}**
    state: present
    comment: "Jay LaCroix"
    password: "{{ jay_passwd }}"
    shell: /bin/bash
```
Regards
